version: '3'

services:
  nginx:
    build: ./Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
  helloworld-service:
    build: ./HelloWorldApi
    expose:
      - "80"
  hellouniverse-service:
    build: ./HelloUniverseApi
    expose:
      - "80"
